// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: chat_api.proto

package chat_server_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatAPIServicesV1Client is the client API for ChatAPIServicesV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatAPIServicesV1Client interface {
	Create(ctx context.Context, in *CreateNewChatRequest, opts ...grpc.CallOption) (*CreateNewChatResponse, error)
	Delete(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type chatAPIServicesV1Client struct {
	cc grpc.ClientConnInterface
}

func NewChatAPIServicesV1Client(cc grpc.ClientConnInterface) ChatAPIServicesV1Client {
	return &chatAPIServicesV1Client{cc}
}

func (c *chatAPIServicesV1Client) Create(ctx context.Context, in *CreateNewChatRequest, opts ...grpc.CallOption) (*CreateNewChatResponse, error) {
	out := new(CreateNewChatResponse)
	err := c.cc.Invoke(ctx, "/chat_server_v1.ChatAPIServicesV1/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatAPIServicesV1Client) Delete(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/chat_server_v1.ChatAPIServicesV1/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatAPIServicesV1Client) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/chat_server_v1.ChatAPIServicesV1/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatAPIServicesV1Server is the server API for ChatAPIServicesV1 service.
// All implementations must embed UnimplementedChatAPIServicesV1Server
// for forward compatibility
type ChatAPIServicesV1Server interface {
	Create(context.Context, *CreateNewChatRequest) (*CreateNewChatResponse, error)
	Delete(context.Context, *DeleteChatRequest) (*emptypb.Empty, error)
	SendMessage(context.Context, *SendMessageRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedChatAPIServicesV1Server()
}

// UnimplementedChatAPIServicesV1Server must be embedded to have forward compatible implementations.
type UnimplementedChatAPIServicesV1Server struct {
}

func (UnimplementedChatAPIServicesV1Server) Create(context.Context, *CreateNewChatRequest) (*CreateNewChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedChatAPIServicesV1Server) Delete(context.Context, *DeleteChatRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedChatAPIServicesV1Server) SendMessage(context.Context, *SendMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatAPIServicesV1Server) mustEmbedUnimplementedChatAPIServicesV1Server() {}

// UnsafeChatAPIServicesV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatAPIServicesV1Server will
// result in compilation errors.
type UnsafeChatAPIServicesV1Server interface {
	mustEmbedUnimplementedChatAPIServicesV1Server()
}

func RegisterChatAPIServicesV1Server(s grpc.ServiceRegistrar, srv ChatAPIServicesV1Server) {
	s.RegisterService(&ChatAPIServicesV1_ServiceDesc, srv)
}

func _ChatAPIServicesV1_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatAPIServicesV1Server).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat_server_v1.ChatAPIServicesV1/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatAPIServicesV1Server).Create(ctx, req.(*CreateNewChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatAPIServicesV1_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatAPIServicesV1Server).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat_server_v1.ChatAPIServicesV1/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatAPIServicesV1Server).Delete(ctx, req.(*DeleteChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatAPIServicesV1_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatAPIServicesV1Server).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat_server_v1.ChatAPIServicesV1/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatAPIServicesV1Server).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatAPIServicesV1_ServiceDesc is the grpc.ServiceDesc for ChatAPIServicesV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatAPIServicesV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat_server_v1.ChatAPIServicesV1",
	HandlerType: (*ChatAPIServicesV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ChatAPIServicesV1_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ChatAPIServicesV1_Delete_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChatAPIServicesV1_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat_api.proto",
}
