version: '3'

volumes:
  postgres_volume:

services:
# pg - name to coonect db from other services
  pg:
    image: postgres:14-alpine3.17
    
    # sets environment variables needed for the PostgreSQL instance to run correctly.
    # These are environment variable placeholders. They will be replaced by the actual 
    # values defined in your environment variables or in a .env file.
    # When you run your Docker Compose stack, Docker will substitute ${PG_DATABASE_NAME}, 
    # ${PG_USER}, and ${PG_PASSWORD} with the values specified in 
    # your environment or in an .env file.

    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"

    # Our Docker container will be accessible on port .env 54321 of your host, 
    # and Docker will redirect requests from this port to port 5432 
    # inside the container, where the PostgreSQL service is expected 
    # to be running. 
    ports:
      - "${PG_PORT}:5432"

      # Volumes Mounts the postgres_volume volume to the /var/lib/postgresql/data 
      # directory within the container. This ensures that the data generated by 
      # the PostgreSQL container is persisted even if the container is stopped or removed.
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  
  # migrations
  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg

# chat

#   chat-db:
#     image: postgres:14
#     container_name: chat-postgres
#     environment:
#       POSTGRES_DB: chat_db
#       POSTGRES_USER: chat_user
#       POSTGRES_PASSWORD: chat_password
#     ports:
#       - "5433:5432"
#     volumes:
#       - chat-db-data:/var/lib/postgresql/data

# volumes:
#   chat-db-data: